### PR TITLE
chore(package): use caret range for `schema-utils` (`dependencies`)

### PR DESCRIPTION
**Pull request by billyjanitsch**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [x] **metadata update**

### Motivation / Use-Case

This will allow url-loader to depend on new, compatible versions of schema-utils as they are released. The other dependencies of url-loader are declared this way. See https://github.com/webpack-contrib/url-loader/pull/136#issuecomment-412967621

### Breaking Changes

n/a

### Additional Info

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
@evilebottnawi Do you have 2FA enable for you npm acc ? Or did it work without 2FA enabled ? If it is still required I need to set it up for my acc first 😛, so if you have the time could you please cut a release?

**Comment by evilebottnawi** [comment]
@michael-ciniawsky yep, enabled, ok :+1:

**Comment by michael-ciniawsky** [comment]
@evilebottnawi Thx, I will enable it as soon as aswell :)

**Pull request merged**
