### PR TITLE
refactor: webpack-defaults

### PR DESCRIPTION
**Pull request by shellscape**
This PR updates the repo to the latest webpack-defaults. Major improvements in tooling, github templates, and metadata.

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@shellscape what is wrong with node9-latest? :confused:

**Comment by shellscape** [comment]
@evilebottnawi all odd-numbered releases of node are not covered by LTS, so they're not officially supported.  see https://github.com/nodejs/Release and search for "odd"

**Comment by evilebottnawi** [comment]
@shellscape i know, just strange what it is hangs, feel free to merge :+1:

**Comment by shellscape** [comment]
@evilebottnawi that's a leftover from the previous circle CI config and is no longer run (only 6, 8 , and 10 now). I believe this can be merged OK

**Comment by evilebottnawi** [comment]
@shellscape can't have access to merge
```
All required statuses and check runs on this pull request must run successfully to enable automatic merging.
```

**Comment by shellscape** [comment]
OK given that we've got approval and you're blocked merging this, I'll use admin privs and merge it.

**Pull request merged**
