### PR TITLE
refactor(package): switch from `@webpack-contrib/schema-utils` to `schema-utils` (`dependencies`)

### LINKED ISSUE #132: Publish latest version to npm
It seems to me that `schema-utils` dep was updated a little while ago, although it wasn't published on npm. I'm getting some annoying warnings after upgrading to webpack 4. What's the plan? Can't a new version be published after #129?

### PR DESCRIPTION
**Pull request by evilebottnawi**
This PR contains a:

- [ ] **bugfix**
- [ ] new **feature**
- [x] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

fixes #132

### Breaking Changes

no

### Additional Info

Need release after merge

### CODE REVIEW

**Comment by michael-ciniawsky** [comment]
👍

**Comment by evilebottnawi** [comment]
@michael-ciniawsky can you do release?

**Comment by michael-ciniawsky** [comment]
Yes, I'm looking through some of the repos and release all pending releases, anything else you are aware of which needs a release asap ? :)

**Comment by evilebottnawi** [comment]
@michael-ciniawsky hm, no, i will release `uglifyjs` new plugin in near time and need release this loader

**Comment by michael-ciniawsky** [comment]
⚠️ I need to force push to `master` here, because of the changelog generation

**Comment by evilebottnawi** [comment]
@michael-ciniawsky you don't have permissions?

**Comment by michael-ciniawsky** [comment]
No the changelog based on the commits (by andrew) is off and I need to reword some of them 😞 , The same happend in `source-maps-loader` (bumps a `major` and adds `BREAKING CHANGES` which is wrong) and I need to force push there aswell, it very bad practice to do that normally

I just notified you here, so you are aware when `git fetch/git pull` etc the next time :)

**Comment by billyjanitsch** [comment]
@evilebottnawi @michael-ciniawsky could you please declare the schema-utils dependency with a caret range instead of an exact version, like the other dependencies? :) I can make the PR if you want.

**Comment by evilebottnawi** [comment]
@billyjanitsch oh, sorry, my mistake, can you send new PR with fix?

**Pull request merged**
