### PR TITLE
Make file-loader an actual dependency

### PR DESCRIPTION
**Pull request by kyleholzinger**
**What kind of change does this PR introduce?**

This change moves the `file-loader` peer dependency to an actual production dependency

**Did you add tests for your changes?**
No

**If relevant, did you update the README?**
No

**Summary**

According to [the official announcement by nodeJS](https://nodejs.org/en/blog/npm/peer-dependencies/), peer dependencies should only be used for plugins. While `url-loader` serves a very similar purpose to `file-loader`, it does not augment or extend `file-loader` and actually serves as a full replacement. That being said, I could always be misunderstanding the purpose of this loader or what the definition of peer dependencies are If I'm totally off base then of course feel free to just close this PR! 

**Does this PR introduce a breaking change?**

No

**Other information**
I opened a PR instead of an issue so that if you guys agree you can merge it super easily without having to do the silly `npm install` yourselves, and if you disagree you can close it. Thanks for an awesome compiler!

### CODE REVIEW

**Comment by evilebottnawi** [comment]
@kyleholzinger why? `file-loader` in peerDeps so that developers can directly chose required version of `file-loader`.

**Comment by kyleholzinger** [comment]
Interesting, that totally makes sense. Do you think there are situations where someone would _sometimes_ use `url-loader` and other times use `file-loader`? Otherwise I feel like it'd make sense to have `url-loader` declare the version of `file-loader`

**Comment by evilebottnawi** [comment]
@kyleholzinger yep.
1. I don't want to waste time in dev mode on `content.toString("base64")` (also some other loader can spend a lot of time). Just example. 
```js
{
    test: /\.(eot|ttf|otf|woff2?)$/,
    loader: isProductionEnv ? 'url-loader' : 'file-loader'
}
```

2. Also, some can use their forks and branches `"css-loader": "git+https://github.com/evilebottnawi/file-loader#super-perf-using-super-fast-fs",`. Look `sass-loader`, he use `node-sass` as peerDeps, it is allow developments to choose required version.

**Comment by kyleholzinger** [comment]
Ahh I see. Would that really be a use case for having `file-loader` as a peer dep though? It seems like doing that is a conscious choice, whereas if you require `file-loader` to be a peer, then even if you don't directly use `file-loader` you still need to have it installed and it can be difficult to pin down if it can be removed or not. Maybe that's just because I've had a lot of pain trying to clean up my package.json and peer deps adds a whole other layer of complexity to your dependency graph, but I've always tried to stray away peer deps unless absolutely necessary 😛  As I said though, if people disagree I'd be more than happy to close this. Whatever makes everyones' lives easier!

**Comment by d3viant0ne** [comment]
@kyleholzinger - As a general rule, we avoid making loaders depend on loaders ( see reasons above )

**Pull request closed without merging**
